# Generated by Django 4.2.2 on 2023-07-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibblio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="books_to_read",
            field=models.ManyToManyField(
                blank=True, related_name="in_to_read", to="bibblio.book"
            ),
        ),
    ]
