# Generated by Django 4.2.2 on 2023-08-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibblio", "0004_rename_image_url_book_cover_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image_url",
            field=models.URLField(
                default="https://www.mobileread.com/forums/attachment.php?attachmentid=111282&d=1378756884"
            ),
        ),
    ]
