# Generated by Django 4.2.2 on 2023-08-04 21:18

import bibblio.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibblio", "0005_alter_book_cover_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image_url",
            field=models.URLField(
                default=bibblio.models.Book.get_default_cover_image_url
            ),
        ),
    ]
