# Generated by Django 4.2.2 on 2023-07-29 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bibblio", "0003_alter_book_authors_alter_book_publication_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="image_url",
            new_name="cover_image_url",
        ),
    ]
